### PR TITLE
Similar to fix #167 but for PUT call

### LINKED ISSUE #167: The library should not cause a JSONDecodeError
Just got the following backtrace:

       r = client.lists.members.all(list_id=list_id, get_all=True, fields="members.id,members.status,members.last_changed,members.interests,members.merge_fields")
      File ".../mailchimp3/entities/listmembers.py", line 94, in all
        return self._iterate(url=self._build_path(list_id, 'members'), **queryparams)
      File ".../mailchimp3/baseapi.py", line 60, in _iterate
        result = self._mc_client._get(url=url, offset=0, count=5000, **queryparams)
      File ".../mailchimp3/mailchimpclient.py", line 29, in wrapper
        return fn(self, *args, **kwargs)
      File ".../mailchimp3/mailchimpclient.py", line 157, in _get
        raise MailChimpError(r.json())
      File "/usr/lib/python3/dist-packages/requests/models.py", line 892, in json
        return complexjson.loads(self.text, **kwargs)
      File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I can't be sure, but it appears to have been a transient problem with a MailChimp server.

Given that these things seem to happen, I think the library should do something reasonable, i.e. catch the JSON decode error and instead return the response. Something like

            if r.status_code >= 400:
                try:
                    error_data = r.json()
                except json.decoder.JSONDecodeError:
                    error_data = { "response": r }
                raise MailChimpError(error_data)

Then we get to see the actual error and can handle it, somehow, instead of getting back an opaque decode exception.

### PR DESCRIPTION
**Pull request by Remiz**
I noticed that same issue as described in #167 but this time for a PUT call. I applied the same fix as commit 3377ea982d6b541fa61ff55dfea42643598a27de

### CODE REVIEW

**Comment by stephenross** [comment]
Please update the version number in the setup and readme files and then this can be merged

**Comment by Remiz** [comment]
Done!

**Comment by stephenross** [comment]
@charlesthk If you could please update PyPi with the shiny new changes for 3.0.7

**Comment by charlesthk** [comment]
@stephenross 3.0.7 is now on PyPi, thanks !

**Pull request merged**
